vim.lsp.enable('bashls')
vim.lsp.enable('docker_compose_language_service')
vim.lsp.enable('dockerls')
vim.lsp.enable('dotls')
vim.lsp.enable('gopls')
vim.lsp.enable('html')
vim.lsp.enable('java_language_server')
vim.lsp.enable('lua_ls')
vim.lsp.enable('nginx_language_server')
vim.lsp.enable('ts_ls')

